version: "3.8"
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: singla
      POSTGRES_USER: singlaadmin
      POSTGRES_PASSWORD: singlapassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
